{
 "title": "monitorando-k8s",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Lifecycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deployment Ready Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"coffee-shop-deployment\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ReplicaSet Replicas Quantity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_replicaset_status_replicas{namespace=\"$namespace\"} >= 1",
     "legendFormat": "{{replicaset}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=\"$namespace\", condition=\"true\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicaset Ready Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(kube_replicaset_status_ready_replicas{namespace=\"$namespace\"} >= 0)\n\nand\n\n(kube_replicaset_status_fully_labeled_replicas{namespace=\"$namespace\"} > 0)",
     "legendFormat": "{{replicaset}}"
    }
   ]
  }
 ]
}