apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  sessionAffinity: ClientIP
  selector:
    app: my-app
  type: ClusterIP
  ports:
    - name: http-8080-80
      port: 8080
      targetPort: 80
      protocol: TCP
    - name: https-8443-443
      port: 8443
      targetPort: 443
      protocol: TCP
