apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  sessionAffinity: ClientIP # all client(IP Address) request are forwarded to the same Pod
  selector:
    app: my-app
  type: ClusterIP
  ports:
    - name: svc-http
      port: 8080
      targetPort: 80
      protocol: TCP
