controller:
  terminationGracePeriodSeconds: 0
  watchIngressWithoutClass: true  

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  hostPort:
    enabled: true

  service:
    type: LoadBalancer

  nodeSelector:
    ingress-ready: "true"

  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      effect: "NoSchedule"

  publishService:
    enabled: true
