apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 5
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-deploy-ctnr
          image: nginx
          ports:
            - name: http-80
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            successThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 5
      restartPolicy: Always
