apiVersion: v1
kind: Service
metadata:
  name: my-headless-svc
spec:
  clusterIP: None  # define Service as Headless
  selector:
    app: my-app
  ports:
    - name: http-8080
      port: 8080
      targetPort: 80
